"use client";

import ToolCard from "./ToolCard";
import {
  FileText,
  Image as ImageIcon,
  Scissors,
  Minimize2,
  Lock,
  Unlock,
  FileEdit,
  Grid3x3,
  FileSignature,
  Crop,
  Eye,
  Settings,
  Shield,
  Combine,
  Download,
  Upload,
  FileImage,
  FileType,
  Scan,
  Type,
  Maximize2,
  RotateCw,
  Trash2,
  Check,
  FileJson,
  Code,
  Languages,
  Camera,
  Volume2,
  Sparkles,
  Layers,
  Move,
  ZoomIn,
  FileSpreadsheet,
  Database,
  Hash,
  Ruler,
  Frame,
  Binary,
  FileCode,
  Palette,
  Filter,
  AlertCircle,
  Sheet,
  Boxes,
  ScanLine,
  ListOrdered,
  Eraser,
  AlignLeft,
} from "lucide-react";

export default function ToolsGrid() {
  const tools = [
    {
      title: "Merge PDF",
      description: "Combine multiple PDF files into one document",
      href: "/tools/merge-pdf",
      icon: Combine,
      gradient: "from-pink-500 to-rose-600",
    },
    {
      title: "Merge PDF and Images",
      description: "Combine PDF files and images into one document",
      href: "/tools/merge-pdf-and-images",
      icon: Layers,
      gradient: "from-purple-500 to-pink-600",
    },
    {
      title: "Merge PDF Text",
      description: "Merge text content from multiple PDFs",
      href: "/tools/merge-pdf-text",
      icon: Type,
      gradient: "from-indigo-500 to-blue-600",
    },
    {
      title: "Split PDF",
      description: "Split PDF into multiple separate files",
      href: "/tools/split-pdf-online",
      icon: Scissors,
      gradient: "from-green-500 to-emerald-600",
    },
    {
      title: "Split PDF Into Parts",
      description: "Divide PDF into specific number of parts",
      href: "/tools/split-pdf-into-parts",
      icon: Grid3x3,
      gradient: "from-teal-500 to-green-600",
    },
    {
      title: "Split PDF Text",
      description: "Extract and split text from PDF pages",
      href: "/tools/split-pdf-text",
      icon: AlignLeft,
      gradient: "from-cyan-500 to-teal-600",
    },
    {
      title: "Compress PDF",
      description: "Reduce PDF file size while maintaining quality",
      href: "/tools/compress-pdf",
      icon: Minimize2,
      gradient: "from-purple-500 to-violet-600",
    },
    {
      title: "Hyper Compress PDF",
      description: "Maximum compression for smallest file size",
      href: "/tools/hyper-compress-pdf",
      icon: Maximize2,
      gradient: "from-violet-500 to-purple-700",
    },
    {
      title: "Protect PDF",
      description: "Add password protection to your PDF files",
      href: "/tools/protect-pdf",
      icon: Lock,
      gradient: "from-orange-500 to-amber-600",
    },
    {
      title: "Add Watermark",
      description: "Add text or image watermarks to PDF",
      href: "/tools/add-watermark-to-pdf",
      icon: FileSignature,
      gradient: "from-indigo-500 to-purple-600",
    },
    {
      title: "Add Text to PDF",
      description: "Insert custom text anywhere in your PDF",
      href: "/tools/add-text-to-pdf",
      icon: Type,
      gradient: "from-blue-500 to-indigo-600",
    },
    {
      title: "Add Blank Pages",
      description: "Insert blank pages into your PDF",
      href: "/tools/add-blank-pages-to-pdf",
      icon: FileText,
      gradient: "from-blue-500 to-cyan-600",
    },
    {
      title: "Add Page Numbers",
      description: "Add page numbers to your PDF documents",
      href: "/tools/add-page-number-to-pdf",
      icon: Hash,
      gradient: "from-emerald-500 to-green-600",
    },
    {
      title: "Add PDF Metadata",
      description: "Add or edit PDF metadata and properties",
      href: "/tools/add-pdf-meta-data",
      icon: Database,
      gradient: "from-slate-500 to-gray-600",
    },
    {
      title: "Add Stroke to PDF",
      description: "Add borders and strokes to PDF elements",
      href: "/tools/add-stroke-to-pdf",
      icon: Frame,
      gradient: "from-amber-500 to-yellow-600",
    },
    {
      title: "Crop PDF",
      description: "Crop and trim PDF pages",
      href: "/tools/crop-pdf",
      icon: Crop,
      gradient: "from-amber-500 to-orange-600",
    },
    {
      title: "Crop PDF Online",
      description: "Online PDF cropping tool",
      href: "/tools/crop-pdf-online",
      icon: Crop,
      gradient: "from-orange-500 to-red-600",
    },
    {
      title: "Rotate PDF",
      description: "Rotate PDF pages in any direction",
      href: "/tools/rotate-pdf",
      icon: RotateCw,
      gradient: "from-purple-500 to-pink-600",
    },
    {
      title: "Reverse PDF",
      description: "Reverse the order of PDF pages",
      href: "/tools/reverse-pdf",
      icon: RotateCw,
      gradient: "from-fuchsia-500 to-purple-600",
    },
    {
      title: "View PDF",
      description: "View and read PDF files online",
      href: "/tools/pdf-reader",
      icon: Eye,
      gradient: "from-emerald-500 to-teal-600",
    },
    {
      title: "Extract PDF Pages",
      description: "Extract specific pages from PDF",
      href: "/tools/extract-pdf-pages",
      icon: Scissors,
      gradient: "from-lime-500 to-emerald-600",
    },
    {
      title: "Remove PDF Pages",
      description: "Delete unwanted pages from PDF",
      href: "/tools/remove-pdf-pages",
      icon: Trash2,
      gradient: "from-red-500 to-rose-600",
    },
    {
      title: "Extract Images",
      description: "Extract all images from PDF files",
      href: "/tools/extract-images-from-pdf",
      icon: ImageIcon,
      gradient: "from-pink-500 to-fuchsia-600",
    },
    {
      title: "Image to PDF",
      description: "Convert images to PDF format",
      href: "/tools/image-to-pdf-converter",
      icon: ImageIcon,
      gradient: "from-fuchsia-500 to-pink-600",
    },
    {
      title: "JPG to PDF",
      description: "Convert JPG images to PDF",
      href: "/tools/jpg-to-pdf",
      icon: FileImage,
      gradient: "from-rose-500 to-pink-600",
    },
    {
      title: "PNG to PDF",
      description: "Convert PNG images to PDF",
      href: "/tools/png-to-pdf-converter",
      icon: FileImage,
      gradient: "from-blue-500 to-cyan-600",
    },
    {
      title: "WebP to PDF",
      description: "Convert WebP images to PDF",
      href: "/tools/webp-to-pdf-converter",
      icon: FileImage,
      gradient: "from-green-500 to-teal-600",
    },
    {
      title: "SVG to PDF",
      description: "Convert SVG vector graphics to PDF",
      href: "/tools/svg-to-pdf-converter",
      icon: FileImage,
      gradient: "from-violet-500 to-purple-600",
    },
    {
      title: "ICO to PDF",
      description: "Convert ICO icons to PDF",
      href: "/tools/ico-to-pdf",
      icon: FileImage,
      gradient: "from-amber-500 to-orange-600",
    },
    {
      title: "TGA to PDF",
      description: "Convert TGA images to PDF",
      href: "/tools/tga-to-pdf-converter",
      icon: FileImage,
      gradient: "from-indigo-500 to-blue-600",
    },
    {
      title: "PSD to PDF",
      description: "Convert Photoshop PSD files to PDF",
      href: "/tools/psd-to-pdf-converter",
      icon: Palette,
      gradient: "from-blue-500 to-purple-600",
    },
    {
      title: "PSB to PDF",
      description: "Convert large Photoshop PSB files to PDF",
      href: "/tools/psb-to-pdf",
      icon: Palette,
      gradient: "from-purple-500 to-pink-600",
    },
    {
      title: "PDF to JPG",
      description: "Convert PDF pages to JPG images",
      href: "/tools/pdf-to-jpg",
      icon: FileImage,
      gradient: "from-cyan-500 to-blue-600",
    },
    {
      title: "PDF to PNG",
      description: "Convert PDF pages to PNG images",
      href: "/tools/pdf-to-png",
      icon: FileImage,
      gradient: "from-teal-500 to-cyan-600",
    },
    {
      title: "PDF to Image",
      description: "Convert PDF to various image formats",
      href: "/tools/pdf-to-image-converter",
      icon: ImageIcon,
      gradient: "from-pink-500 to-rose-600",
    },
    {
      title: "PDF to WebP",
      description: "Convert PDF to WebP format",
      href: "/tools/pdf-to-webp-converter",
      icon: FileImage,
      gradient: "from-emerald-500 to-green-600",
    },
    {
      title: "PDF to TIFF",
      description: "Convert PDF to TIFF format",
      href: "/tools/pdf-to-tiff",
      icon: FileImage,
      gradient: "from-slate-500 to-zinc-600",
    },
    {
      title: "PDF to PSD",
      description: "Convert PDF to Photoshop PSD",
      href: "/tools/pdf-to-psd",
      icon: Palette,
      gradient: "from-violet-500 to-fuchsia-600",
    },
    {
      title: "PDF to ICO",
      description: "Convert PDF to ICO icon format",
      href: "/tools/pdf-to-ico",
      icon: FileImage,
      gradient: "from-orange-500 to-amber-600",
    },
    {
      title: "PDF to TGA",
      description: "Convert PDF to TGA format",
      href: "/tools/pdf-to-tga",
      icon: FileImage,
      gradient: "from-blue-500 to-indigo-600",
    },
    {
      title: "PDF to EPS",
      description: "Convert PDF to EPS vector format",
      href: "/tools/pdf-to-eps",
      icon: FileImage,
      gradient: "from-purple-500 to-violet-600",
    },
    {
      title: "Word to PDF",
      description: "Convert Word documents to PDF",
      href: "/tools/word-to-pdf",
      icon: FileType,
      gradient: "from-blue-500 to-sky-600",
    },
    {
      title: "Word to PDF Simple",
      description: "Simple Word to PDF converter",
      href: "/tools/word-to-pdf-simple",
      icon: FileType,
      gradient: "from-sky-500 to-blue-600",
    },
    {
      title: "Word URL to PDF",
      description: "Convert Word documents from URL to PDF",
      href: "/tools/word-url-to-pdf",
      icon: Download,
      gradient: "from-indigo-500 to-purple-600",
    },
    {
      title: "PDF to Word",
      description: "Convert PDF to Word documents",
      href: "/tools/convert-pdf-to-word",
      icon: FileType,
      gradient: "from-cyan-500 to-blue-600",
    },
    {
      title: "PDF to Word Simple",
      description: "Simple PDF to Word converter",
      href: "/tools/pdf-to-word-simple",
      icon: FileType,
      gradient: "from-blue-500 to-cyan-600",
    },
    {
      title: "Excel to PDF",
      description: "Convert Excel spreadsheets to PDF",
      href: "/tools/excel-to-pdf",
      icon: FileSpreadsheet,
      gradient: "from-green-500 to-emerald-600",
    },
    {
      title: "Convert Excel to PDF",
      description: "Advanced Excel to PDF conversion",
      href: "/tools/convert-excel-to-pdf",
      icon: FileSpreadsheet,
      gradient: "from-emerald-500 to-teal-600",
    },
    {
      title: "PDF to Excel",
      description: "Convert PDF to Excel spreadsheets",
      href: "/tools/convert-pdf-to-excel",
      icon: FileSpreadsheet,
      gradient: "from-teal-500 to-green-600",
    },
    {
      title: "PDF to Excel Simple",
      description: "Simple PDF to Excel converter",
      href: "/tools/pdf-to-excel-simple",
      icon: FileSpreadsheet,
      gradient: "from-green-500 to-lime-600",
    },
    {
      title: "Spreadsheet to PDF",
      description: "Convert any spreadsheet to PDF",
      href: "/tools/spreadsheet-to-pdf",
      icon: Sheet,
      gradient: "from-lime-500 to-green-600",
    },
    {
      title: "HTML to PDF",
      description: "Convert HTML web pages to PDF",
      href: "/tools/html-to-pdf",
      icon: Code,
      gradient: "from-orange-500 to-red-600",
    },
    {
      title: "PDF to HTML",
      description: "Convert PDF to HTML format",
      href: "/tools/pdf-to-html",
      icon: Code,
      gradient: "from-red-500 to-orange-600",
    },
    {
      title: "Markdown to PDF",
      description: "Convert Markdown files to PDF",
      href: "/tools/markdown-to-pdf",
      icon: FileCode,
      gradient: "from-slate-500 to-gray-600",
    },
    {
      title: "PDF to Markdown",
      description: "Convert PDF to Markdown format",
      href: "/tools/pdf-to-markdown",
      icon: FileCode,
      gradient: "from-gray-500 to-slate-600",
    },
    {
      title: "Text to PDF",
      description: "Convert plain text to PDF",
      href: "/tools/text-to-pdf-converter",
      icon: Type,
      gradient: "from-zinc-500 to-gray-600",
    },
    {
      title: "PDF to Text",
      description: "Extract text content from PDF",
      href: "/tools/pdf-to-text",
      icon: Type,
      gradient: "from-gray-500 to-zinc-600",
    },
    {
      title: "TXT to PDF",
      description: "Convert TXT files to PDF",
      href: "/tools/txt-to-pdf-converter",
      icon: FileText,
      gradient: "from-neutral-500 to-stone-600",
    },
    {
      title: "RTF to PDF",
      description: "Convert Rich Text Format to PDF",
      href: "/tools/rtf-to-pdf-converter",
      icon: FileType,
      gradient: "from-amber-500 to-yellow-600",
    },
    {
      title: "PDF to RTF",
      description: "Convert PDF to Rich Text Format",
      href: "/tools/pdf-to-rtf",
      icon: FileType,
      gradient: "from-yellow-500 to-amber-600",
    },
    {
      title: "JSON to PDF",
      description: "Convert JSON data to PDF",
      href: "/tools/json-to-pdf",
      icon: FileJson,
      gradient: "from-emerald-500 to-teal-600",
    },
    {
      title: "PDF to JSON",
      description: "Convert PDF to JSON format",
      href: "/tools/pdf-to-json",
      icon: FileJson,
      gradient: "from-teal-500 to-emerald-600",
    },
    {
      title: "XML to PDF",
      description: "Convert XML files to PDF",
      href: "/tools/xml-to-pdf-converter",
      icon: Code,
      gradient: "from-rose-500 to-pink-600",
    },
    {
      title: "PDF to XML",
      description: "Convert PDF to XML format",
      href: "/tools/pdf-to-xml-converter",
      icon: Code,
      gradient: "from-pink-500 to-rose-600",
    },
    {
      title: "YAML to PDF",
      description: "Convert YAML files to PDF",
      href: "/tools/yaml-to-pdf-converter",
      icon: FileCode,
      gradient: "from-purple-500 to-fuchsia-600",
    },
    {
      title: "PDF to YAML",
      description: "Convert PDF to YAML format",
      href: "/tools/pdf-to-yaml-converter",
      icon: FileCode,
      gradient: "from-fuchsia-500 to-purple-600",
    },
    {
      title: "CSV to PDF",
      description: "Convert CSV data to PDF tables",
      href: "/tools/csv-to-pdf",
      icon: FileSpreadsheet,
      gradient: "from-green-500 to-teal-600",
    },
    {
      title: "TSV to PDF",
      description: "Convert TSV data to PDF",
      href: "/tools/tsv-to-pdf",
      icon: FileSpreadsheet,
      gradient: "from-teal-500 to-cyan-600",
    },
    {
      title: "SRT to PDF",
      description: "Convert subtitle SRT files to PDF",
      href: "/tools/srt-to-pdf-converter",
      icon: FileText,
      gradient: "from-violet-500 to-purple-600",
    },
    {
      title: "VTT to PDF",
      description: "Convert WebVTT subtitle files to PDF",
      href: "/tools/vtt-to-pdf-converter",
      icon: FileText,
      gradient: "from-purple-500 to-violet-600",
    },
    {
      title: "Base64 to PDF",
      description: "Decode Base64 strings to PDF",
      href: "/tools/base64-to-pdf",
      icon: Binary,
      gradient: "from-slate-500 to-zinc-600",
    },
    {
      title: "PDF to Base64",
      description: "Encode PDF files to Base64",
      href: "/tools/pdf-to-base64",
      icon: Binary,
      gradient: "from-zinc-500 to-slate-600",
    },
    {
      title: "PDF to RAW",
      description: "Convert PDF to RAW image format",
      href: "/tools/pdf-to-raw",
      icon: FileImage,
      gradient: "from-stone-500 to-neutral-600",
    },
    {
      title: "PDF to ZIP",
      description: "Convert and compress PDF pages to ZIP",
      href: "/tools/pdf-to-zip-converter",
      icon: Boxes,
      gradient: "from-amber-500 to-orange-600",
    },
    {
      title: "PDF to PDF/A",
      description: "Convert to PDF/A archival format",
      href: "/tools/pdf-to-pdfa",
      icon: Shield,
      gradient: "from-blue-500 to-indigo-600",
    },
    {
      title: "OCR PDF",
      description: "Extract text from scanned PDFs using OCR",
      href: "/tools/ocr-pdf",
      icon: Scan,
      gradient: "from-indigo-500 to-purple-600",
    },
    {
      title: "Enhance PDF",
      description: "Improve PDF quality and readability",
      href: "/tools/enhance-pdf",
      icon: Sparkles,
      gradient: "from-yellow-500 to-orange-600",
    },
    {
      title: "Blur PDF",
      description: "Apply blur effects to PDF content",
      href: "/tools/blur-pdf",
      icon: Filter,
      gradient: "from-purple-500 to-pink-600",
    },
    {
      title: "Grayscale PDF",
      description: "Convert PDF to grayscale/black & white",
      href: "/tools/grayscale-pdf",
      icon: Palette,
      gradient: "from-gray-500 to-slate-600",
    },
    {
      title: "Sign PDF",
      description: "Add digital signatures to PDF",
      href: "/tools/sign-pdf",
      icon: FileSignature,
      gradient: "from-blue-500 to-purple-600",
    },
    {
      title: "Redact PDF",
      description: "Remove sensitive information from PDF",
      href: "/tools/redact-pdf",
      icon: Eraser,
      gradient: "from-red-500 to-orange-600",
    },
    {
      title: "Validate PDF",
      description: "Check PDF file integrity and compliance",
      href: "/tools/validate-pdf",
      icon: Check,
      gradient: "from-green-500 to-emerald-600",
    },
    {
      title: "Translate PDF",
      description: "Translate PDF text to different languages",
      href: "/tools/translate-pdf-text",
      icon: Languages,
      gradient: "from-blue-500 to-cyan-600",
    },
    {
      title: "Camera to PDF",
      description: "Capture and convert camera images to PDF",
      href: "/tools/camera-to-pdf",
      icon: Camera,
      gradient: "from-purple-500 to-pink-600",
    },
    {
      title: "Speech to PDF",
      description: "Convert speech/audio to text PDF",
      href: "/tools/speech-text-to-pdf",
      icon: Volume2,
      gradient: "from-orange-500 to-red-600",
    },
    {
      title: "Generate PDF",
      description: "Create custom PDF documents from scratch",
      href: "/tools/generate-pdf",
      icon: Sparkles,
      gradient: "from-cyan-500 to-blue-600",
    },
    {
      title: "Rescale PDF",
      description: "Change PDF page dimensions and scale",
      href: "/tools/rescale-pdf",
      icon: Maximize2,
      gradient: "from-teal-500 to-green-600",
    },
    {
      title: "PDF DPI Changer",
      description: "Adjust PDF image resolution (DPI)",
      href: "/tools/pdf-dpi-changer",
      icon: Settings,
      gradient: "from-indigo-500 to-blue-600",
    },
    {
      title: "PDF Margin Adjuster",
      description: "Modify PDF page margins",
      href: "/tools/pdf-margin-adjuster",
      icon: Ruler,
      gradient: "from-violet-500 to-purple-600",
    },
  ];

  return (
<section className="relative py-20 px-4 overflow-hidden bg-white" id="features">
  {/* Background Pattern */}
  <div className="absolute inset-0">
    <div className="absolute inset-0 bg-[linear-gradient(rgba(251,146,60,0.03)_1px,transparent_1px),linear-gradient(90deg,rgba(251,146,60,0.03)_1px,transparent_1px)] bg-[size:50px_50px]" />
  </div>

  <div className="relative z-10 max-w-7xl mx-auto">
    {/* Section Header */}
    <div className="text-center mb-16">
      <h2 className="text-4xl sm:text-5xl font-bold mb-4 text-gray-900">
        Powerful <span className="text-orange-500">PDF Tools</span>
      </h2>
      <p className="text-gray-600 text-lg max-w-2xl mx-auto">
        Everything you need to work with PDFs - {tools.length}+ tools, all in one place
      </p>
    </div>

    {/* Tools Grid */}
    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
      {tools.map((tool, index) => (
        <ToolCard key={tool.title} {...tool} index={index} />
      ))}
    </div>
  </div>
</section>
  );
}