import {
  FileText,
  Image as ImageIcon,
  Scissors,
  Minimize2,
  Lock,
  Grid3x3,
  FileSignature,
  Crop,
  Eye,
  Combine,
  FileImage,
  FileType,
  Type,
  Maximize2,
  RotateCw,
  Trash2,
  FileJson,
  Languages,
  Layers,
  FileSpreadsheet,
  Database,
  Hash,
  Frame,
  AlignLeft,
  Edit,
  LucideIcon,
} from "lucide-react";

export interface Tool {
  title: string;
  description: string;
  href: string;
  icon: LucideIcon;
  gradient: string;
  category: string;
}

export const allTools: Tool[] = [
  {
    title: "Word to PDF",
    description: "Convert Word documents to PDF",
    href: "/tools/word-to-pdf",
    icon: FileType,
    gradient: "from-blue-500 to-sky-600",
    category: "Convert",
  },
  {
    title: "PDF to Word",
    description: "Convert PDF to Word documents",
    href: "/tools/convert-pdf-to-word",
    icon: FileType,
    gradient: "from-cyan-500 to-blue-600",
    category: "Convert",
  },
  {
    title: "Merge PDF",
    description: "Combine multiple PDF files into one document",
    href: "/tools/merge-pdf",
    icon: Combine,
    gradient: "from-pink-500 to-rose-600",
    category: "Organize",
  },
  {
    title: "Split PDF",
    description: "Split PDF into multiple separate files",
    href: "/tools/split-pdf-online",
    icon: Scissors,
    gradient: "from-green-500 to-emerald-600",
    category: "Organize",
  },
  {
    title: "Compress PDF",
    description: "Reduce PDF file size while maintaining quality",
    href: "/tools/compress-pdf",
    icon: Minimize2,
    gradient: "from-purple-500 to-violet-600",
    category: "Optimize",
  },
  {
    title: "JPG to PDF",
    description: "Convert JPG images to PDF",
    href: "/tools/jpg-to-pdf",
    icon: FileImage,
    gradient: "from-rose-500 to-pink-600",
    category: "Convert",
  },

  {
    title: "PDF to JPG",
    description: "Convert PDF pages to JPG images",
    href: "/tools/pdf-to-jpg",
    icon: FileImage,
    gradient: "from-cyan-500 to-blue-600",
    category: "Convert",
  },





  {
    title: "Merge PDF and Images",
    description: "Combine PDF files and images into one document",
    href: "/tools/merge-pdf-and-images",
    icon: Layers,
    gradient: "from-purple-500 to-pink-600",
    category: "Organize",
  },
  {
    title: "Merge PDF Text",
    description: "Merge text content from multiple PDFs",
    href: "/tools/merge-pdf-text",
    icon: Type,
    gradient: "from-indigo-500 to-blue-600",
    category: "Organize",
  },

  {
    title: "Split PDF Into Parts",
    description: "Divide PDF into specific number of parts",
    href: "/tools/split-pdf-into-parts",
    icon: Grid3x3,
    gradient: "from-teal-500 to-green-600",
    category: "Organize",
  },
  {
    title: "Split PDF Text",
    description: "Extract and split text from PDF pages",
    href: "/tools/split-pdf-text",
    icon: AlignLeft,
    gradient: "from-cyan-500 to-teal-600",
    category: "Organize",
  },

  {
    title: "Edit PDF",
    description: "Add annotations, text, and drawings to your PDF",
    href: "/tools/edit-pdf",
    icon: Edit,
    gradient: "from-green-500 to-teal-600",
    category: "Edit",
  },
  {
    title: "Hyper Compress PDF",
    description: "Maximum compression for smallest file size",
    href: "/tools/hyper-compress-pdf",
    icon: Maximize2,
    gradient: "from-violet-500 to-purple-700",
    category: "Optimize",
  },
  {
    title: "Protect PDF",
    description: "Add password protection to your PDF files",
    href: "/tools/protect-pdf",
    icon: Lock,
    gradient: "from-orange-500 to-amber-600",
    category: "Security",
  },
  {
    title: "Add Watermark",
    description: "Add text or image watermarks to PDF",
    href: "/tools/add-watermark-to-pdf",
    icon: FileSignature,
    gradient: "from-indigo-500 to-purple-600",
    category: "Edit",
  },
  {
    title: "Add Text to PDF",
    description: "Insert custom text anywhere in your PDF",
    href: "/tools/add-text-to-pdf",
    icon: Type,
    gradient: "from-blue-500 to-indigo-600",
    category: "Edit",
  },
  {
    title: "Add Blank Pages",
    description: "Insert blank pages into your PDF",
    href: "/tools/add-blank-pages-to-pdf",
    icon: FileText,
    gradient: "from-blue-500 to-cyan-600",
    category: "Edit",
  },
  {
    title: "Add Page Numbers",
    description: "Add page numbers to your PDF documents",
    href: "/tools/add-page-number-to-pdf",
    icon: Hash,
    gradient: "from-emerald-500 to-green-600",
    category: "Edit",
  },
  {
    title: "Add PDF Metadata",
    description: "Add or edit PDF metadata and properties",
    href: "/tools/add-pdf-meta-data",
    icon: Database,
    gradient: "from-slate-500 to-gray-600",
    category: "Edit",
  },
  {
    title: "Add Stroke to PDF",
    description: "Add borders and strokes to PDF elements",
    href: "/tools/add-stroke-to-pdf",
    icon: Frame,
    gradient: "from-amber-500 to-yellow-600",
    category: "Edit",
  },
  {
    title: "Crop PDF",
    description: "Crop and trim PDF pages",
    href: "/tools/crop-pdf",
    icon: Crop,
    gradient: "from-amber-500 to-orange-600",
    category: "Edit",
  },
  {
    title: "Crop PDF Online",
    description: "Online PDF cropping tool",
    href: "/tools/crop-pdf-online",
    icon: Crop,
    gradient: "from-orange-500 to-red-600",
    category: "Edit",
  },
  {
    title: "Rotate PDF",
    description: "Rotate PDF pages in any direction",
    href: "/tools/rotate-pdf",
    icon: RotateCw,
    gradient: "from-purple-500 to-pink-600",
    category: "Edit",
  },
  {
    title: "Reverse PDF",
    description: "Reverse the order of PDF pages",
    href: "/tools/reverse-pdf",
    icon: RotateCw,
    gradient: "from-fuchsia-500 to-purple-600",
    category: "Organize",
  },
  {
    title: "View PDF",
    description: "View and read PDF files online",
    href: "/tools/pdf-reader",
    icon: Eye,
    gradient: "from-emerald-500 to-teal-600",
    category: "View",
  },
  {
    title: "Extract PDF Pages",
    description: "Extract specific pages from PDF",
    href: "/tools/extract-pdf-pages",
    icon: Scissors,
    gradient: "from-lime-500 to-emerald-600",
    category: "Organize",
  },
  {
    title: "Remove PDF Pages",
    description: "Delete unwanted pages from PDF",
    href: "/tools/remove-pdf-pages",
    icon: Trash2,
    gradient: "from-red-500 to-rose-600",
    category: "Organize",
  },
  {
    title: "Extract Images",
    description: "Extract all images from PDF files",
    href: "/tools/extract-images-from-pdf",
    icon: ImageIcon,
    gradient: "from-pink-500 to-fuchsia-600",
    category: "Convert",
  },
  {
    title: "Image to PDF",
    description: "Convert images to PDF format",
    href: "/tools/image-to-pdf-converter",
    icon: ImageIcon,
    gradient: "from-fuchsia-500 to-pink-600",
    category: "Convert",
  },

  {
    title: "PNG to PDF",
    description: "Convert PNG images to PDF",
    href: "/tools/png-to-pdf-converter",
    icon: FileImage,
    gradient: "from-blue-500 to-cyan-600",
    category: "Convert",
  },
  {
    title: "WebP to PDF",
    description: "Convert WebP images to PDF",
    href: "/tools/webp-to-pdf-converter",
    icon: FileImage,
    gradient: "from-green-500 to-teal-600",
    category: "Convert",
  },
  {
    title: "SVG to PDF",
    description: "Convert SVG vector graphics to PDF",
    href: "/tools/svg-to-pdf-converter",
    icon: FileImage,
    gradient: "from-violet-500 to-purple-600",
    category: "Convert",
  },
  {
    title: "ICO to PDF",
    description: "Convert ICO icons to PDF",
    href: "/tools/ico-to-pdf",
    icon: FileImage,
    gradient: "from-amber-500 to-orange-600",
    category: "Convert",
  },
  {
    title: "TGA to PDF",
    description: "Convert TGA images to PDF",
    href: "/tools/tga-to-pdf-converter",
    icon: FileImage,
    gradient: "from-indigo-500 to-blue-600",
    category: "Convert",
  },
  {
    title: "PDF to Image",
    description: "Convert PDF to various image formats",
    href: "/tools/pdf-to-image-converter",
    icon: ImageIcon,
    gradient: "from-pink-500 to-rose-600",
    category: "Convert",
  },

  {
    title: "PDF to PNG",
    description: "Convert PDF pages to PNG images",
    href: "/tools/pdf-to-png",
    icon: FileImage,
    gradient: "from-teal-500 to-cyan-600",
    category: "Convert",
  },
  {
    title: "PDF to WebP",
    description: "Convert PDF to WebP format",
    href: "/tools/pdf-to-webp-converter",
    icon: FileImage,
    gradient: "from-emerald-500 to-green-600",
    category: "Convert",
  },

  {
    title: "Word to PDF Simple",
    description: "Simple Word to PDF converter",
    href: "/tools/word-to-pdf-simple",
    icon: FileType,
    gradient: "from-sky-500 to-blue-600",
    category: "Convert",
  },

  {
    title: "PDF to Word Simple",
    description: "Simple PDF to Word converter",
    href: "/tools/pdf-to-word-simple",
    icon: FileType,
    gradient: "from-blue-500 to-cyan-600",
    category: "Convert",
  },
  {
    title: "Excel to PDF",
    description: "Convert Excel spreadsheets to PDF",
    href: "/tools/excel-to-pdf",
    icon: FileSpreadsheet,
    gradient: "from-green-500 to-emerald-600",
    category: "Convert",
  },
  {
    title: "PDF to Excel",
    description: "Convert PDF to Excel spreadsheets",
    href: "/tools/convert-pdf-to-excel",
    icon: FileSpreadsheet,
    gradient: "from-teal-500 to-green-600",
    category: "Convert",
  },
  {
    title: "Text to PDF",
    description: "Convert plain text to PDF",
    href: "/tools/text-to-pdf-converter",
    icon: Type,
    gradient: "from-zinc-500 to-gray-600",
    category: "Convert",
  },
  {
    title: "PDF to Text",
    description: "Extract text content from PDF",
    href: "/tools/pdf-to-text",
    icon: Type,
    gradient: "from-gray-500 to-zinc-600",
    category: "Convert",
  },
  {
    title: "TXT to PDF",
    description: "Convert TXT files to PDF",
    href: "/tools/txt-to-pdf-converter",
    icon: FileText,
    gradient: "from-neutral-500 to-stone-600",
    category: "Convert",
  },
  {
    title: "JSON to PDF",
    description: "Convert JSON data to PDF",
    href: "/tools/json-to-pdf",
    icon: FileJson,
    gradient: "from-emerald-500 to-teal-600",
    category: "Convert",
  },
  {
    title: "PDF to JSON",
    description: "Convert PDF to JSON format",
    href: "/tools/pdf-to-json",
    icon: FileJson,
    gradient: "from-teal-500 to-emerald-600",
    category: "Convert",
  },
  {
    title: "Sign PDF",
    description: "Add digital signatures to PDF",
    href: "/tools/sign-pdf",
    icon: FileSignature,
    gradient: "from-blue-500 to-purple-600",
    category: "Security",
  },
  {
    title: "Translate PDF",
    description: "Translate PDF text to different languages",
    href: "/tools/translate-pdf-text",
    icon: Languages,
    gradient: "from-blue-500 to-cyan-600",
    category: "Edit",
  },
];
